name: Deploy Laravel App

on:
  push:
    branches:
      - main   # jis branch pe push hote hi deploy karna hai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 103.152.255.230
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/uada_mardan
            ./deploy.sh
